# Generated by Django 5.1 on 2024-08-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
