# Generated by Django 5.1 on 2024-08-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_left',
            field=models.DateField(null=True, blank=True),
        ),
    ]
